// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Gibbs_e_it_no_ann
arma::mat Gibbs_e_it_no_ann(arma::mat beta_mat, arma::mat G_mat, int n_SNP, int n_GibbsStep);
RcppExport SEXP GGPA_Gibbs_e_it_no_ann(SEXP beta_matSEXP, SEXP G_matSEXP, SEXP n_SNPSEXP, SEXP n_GibbsStepSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type beta_mat(beta_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G_mat(G_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_SNP(n_SNPSEXP);
    Rcpp::traits::input_parameter< int >::type n_GibbsStep(n_GibbsStepSEXP);
    __result = Rcpp::wrap(Gibbs_e_it_no_ann(beta_mat, G_mat, n_SNP, n_GibbsStep));
    return __result;
END_RCPP
}
