# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gibbs_e_it_no_ann <- function(beta_mat, G_mat, n_SNP, n_GibbsStep) {
    .Call('GGPA_Gibbs_e_it_no_ann', PACKAGE = 'GGPA', beta_mat, G_mat, n_SNP, n_GibbsStep)
}

